#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : olivier.sachot.Podium                     # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Podium Logger                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Save the rankings and times of all your competitions and those of your friends. Keep some souvenir photos of your podiums.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Olivier Sachot                                
your_link                                 :                     
your_city                                 : Paris                                
email_address                             : podium.logger@orange.fr
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Save all your competitions
    description                           : Save your rankings and times as well as those of your friends.
    fontawesome_icon_name                 : running
    
  - title                                 : Add photos
    description                           : For each competition, add souvenir photos.
    fontawesome_icon_name                 : images

  - title                                 : Easily find your competitions
    description                           : Competitions can be filtered by sport and person. They can be sorted by date, name, rating, speed and distance.
    fontawesome_icon_name                 : sort

  - title                                 : Share your data with your friends.
    description                           : Data can be shared between "Podium Logger" users simply by e-mail.
    fontawesome_icon_name                 : share

  - title                                 : Map
    description                           : Competitions can be viewed on a map.
    fontawesome_icon_name                 : map
  
  - title                                 : Statistics
    description                           : Get statistics on your competitions (total distance, best ranking, ...).
    fontawesome_icon_name                 : table
    
  - title                                 : Smartwatches
    description                           : The data saved in your iPhone using your smartwatch can be used to create competitions.
    fontawesome_icon_name                 : heartbeat

  - title                                 : Export
    description                           : It is possible to export the list of competitions, the map as well as the statistics.
    fontawesome_icon_name                 : file-export



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.5
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerImage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#F2385A"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F2385A"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
